seeds: [69, 720, 24]
datasets:
  # the dataset in auto pytorch
  # - m3_yearly #segment falt
  # - m3_quarterly
  # - m3_monthly
  # - m3_other
  # - m4_quarterly
  # - m4_monthly
  # - m4_weekly
  # - m4_daily
  # - m4_hourly
  # - m4_yearly
  # - tourism_quarterly
  # - tourism_monthly
  # - dominick
  # - weather
  # - hospital
  # - covid_deaths
  # - electricity
  # - kdd_2018
  # - nn5
  # - rossmann
  # - solar
  # - taxi
  # - wiki

  - covid_deaths
  - hospital
  - m3_monthly
  - m3_other
  - m3_quarterly
  - m4_hourly
  - m4_weekly
  - tourism_quarterly
  - tourism_monthly

models:
  # arima: []
  # ets: []
  # prophet: []
  # deepar:
  #   - key: context_length_multiple
  #     values: [1, 2, 4, 8]
  #   - key: [num_layers, num_cells]
  #     values: [[1, 20], [2, 40], [4, 80]]
  mqcnn:
    - key: context_length_multiple
      values: [1, 2, 4, 8]
    - key: [num_filters, kernel_size_first, kernel_size_hidden, kernel_size_last]
      values: [[20, 3, 3, 2], [30, 7, 3, 3], [40, 14, 7, 3]]
