seeds: [42]

datasets:
  # - covid_deaths
  # - m3_quarterly
  # - hospital
  # - tourism_quarterly
  - m4_hourly
  # - m3_other
  # - tourism_monthly
  # - m4_weekly
  # - m3_monthly
  # - nn5
  # - electricity

models:
  autopytorch: 
    # - key: presets
    #   values: [medium_quality]
    - key: run_time
      # values: [43200]
      values: [3600, 7200, 10800, 14400, 18000, 36000]
      # values: [600]
    # - key: eval_metric
    #   values: [mean_wQuantileLoss] # AVAILABLE_METRICS = ["MASE", "MAPE", "sMAPE", "mean_wQuantileLoss", "MSE", "RMSE"]
