seeds: [42]
datasets:
  # all datasets
  # - exchange_rate
  # - electricity
  # - solar
  # - wiki
  # - taxi
  # - m3_monthly
  # - m3_quarterly
  # - m3_yearly
  # - m3_other
  # - m4_hourly
  # - m4_daily
  # - m4_weekly
  # - m4_monthly
  # - m4_quarterly
  # - m4_yearly
  # - m5
  # - tourism_monthly
  # - tourism_quarterly
  # - tourism_yearly
  # - nn5
  # - london_smart_meters
  # - wind_farms
  # - car_parts
  # - dominick
  # - fred_md
  # - san_francisco_traffic
  # - pedestrian_count
  # - hospital
  # - covid_deaths
  # - kdd_2018
  # - cif_2016
  # - australian_electricity_demand
  # - bitcoin
  # - rideshare
  # - vehicle_trips
  # - weather
  # - temperature_rain
  # - m1_yearly
  # - m1_quarterly
  # - m1_monthly
  # - rossmann
  # - walmart
  # - restaurant

  # small datasets
  # - rossmann
  # - covid_deaths
  # - m3_quarterly
  # - hospital
  - solar
  # - tourism_quarterly
  # - m4_hourly
  # - m3_other
  # - tourism_monthly
  # - m4_weekly
  # - m3_monthly
  # - nn5
  # - electricity
  - kdd_2018

models:
  autogluon: 
    - key: presets
      values: [good_quality]
    - key: run_time
      values: [36000]
    - key: eval_metric
      values: [mean_wQuantileLoss]

      # AVAILABLE_METRICS = ["MASE", "MAPE", "sMAPE", "mean_wQuantileLoss", "MSE", "RMSE"]
